Box v1

diff --git a/cabal b/cabal
--- a/cabal
+++ b/cabal
@@ -11,6 +11,9 @@ Commands:
     repl            Start the repl, by default on the the main library source.
     quick           Start the repl directly skipping cabal, this is useful developing
                     across multiple source trees at once.
+    watch           Watches filesystem for changes and stays running, compiles and gives quick feedback.
+                    Similarly to quick needs an entrypoint.
+                    To run tests use '-T EXPR' i.e. './cabal watch test/test.hs -T Test.Pure.tests'
     demo            If this project has a demo application, this builds and runs it.
     exec            If this project has an executable, this builds and runs it.
     tags            Generate tags for this project.
@@ -18,6 +21,8 @@ Commands:
     init            Start a new project.
     update          Cabal update, but limited to retrieving at most once per day.
     clean           Remove compiled artifacts.
+    depend          Dependency organisation tooling check|deep-check|sync.
+    upgrade         Upgrade this cabal extras script.
 EOF
     exit ${status}
 }
@@ -55,22 +60,38 @@ initialize () {
         cabal sandbox ${SANDBOX:-} init
     }
 
-    [ ! -f "$project.submodules" ] || {
-        # submodules initialized if required, the "has it been done before" is pretty crude, but check is useful.
-        cat $project.submodules | while read submodule; do
-            find "$submodule" -maxdepth 2 -name \*.cabal
-        done | grep -q . || (
-            cd $(git rev-parse --show-toplevel)
-            git submodule init
-            git submodule update
-        )
+    PROJECT_ROOT=$(git rev-parse --show-toplevel)
 
-        cat $project.submodules | while read submodule; do
-            if ! grep -q "${submodule}\"" ${SANDBOX_DIR}/add-source-timestamps; then
-                cabal sandbox add-source ${SANDBOX:-} "$submodule"
-            fi
-        done
-    }
+    # init any submodules that we need. Don't worry about explicit submodules
+    # file here, we just want to trust git to tell us things that haven't been
+    # initialized, we really _don't_ want to run this just because a module is
+    # dirty from development changes etc...
+
+    UNINITIALIZED=$(cd "$PROJECT_ROOT" && git submodule | grep "^-" | cut -d ' ' -f 2)
+    for submodule in $UNINITIALIZED; do
+        $(cd "$PROJECT_ROOT" && git submodule update --init $submodule) || exit $?
+    done
+
+    # if there is an explicit submodules file, then use it (hysterical
+    # raisins, compatability or something...), otherwise auto-magicically
+    # discover the sources from the lib directory.
+
+    if [ -f "$project.submodules" ]; then
+        CABAL_SOURCES=$(cat $project.submodules)
+        echo "Using $project.submodules, however this is now optional, You can remove this file if you like and it will be calculated for you."
+    else
+        CABAL_SOURCES=$(cd "$PROJECT_ROOT" && find lib -maxdepth 4 ! -path "lib/*/bin/*" -name \*.cabal | xargs -L 1 dirname)
+    fi
+
+    # We add-sources only if they haven't been added before. We should also
+    # remove them if they aren't needed, but @charleso has promised to do this
+    # so for now we live in anticipation.
+
+    for submodule in $CABAL_SOURCES; do
+        if ! grep -q "${submodule}\"" ${SANDBOX_DIR}/add-source-timestamps; then
+            cabal sandbox add-source ${SANDBOX:-} "$PROJECT_ROOT/$submodule"
+        fi
+    done
 
     # all dependencies installed, and configure been run?
     cabal install -j --only-dependencies --force-reinstalls --enable-tests
@@ -90,7 +111,7 @@ run_build () {
 #
 run_test () {
     initialize
-    cabal test "$@"
+    cabal test --show-details=streaming "$@"
 }
 
 #
@@ -102,16 +123,51 @@ run_repl () {
 }
 
 #
+# Upgrade the script in place
+#
+run_upgrade () {
+    echo "Checking for a new version of cabal extras ..."
+    TZ=$(date +"%T")
+    curl --silent "https://raw.githubusercontent.com/ambiata/cabal-extras/master/src/cabal?$TZ" > /tmp/cabal
+    COMMIT_VERSION=$(git ls-remote  https://github.com/ambiata/cabal-extras | grep refs/heads/master | cut -f 1)
+    echo "# Version: $COMMIT_VERSION" >> /tmp/cabal
+    if ! cmp ./cabal /tmp/cabal  >/dev/null 2>&1
+    then
+      echo "New version found and upgraded. You can now commit it to your git repo."
+      mv /tmp/cabal ./cabal
+      chmod +x ./cabal
+    else
+      echo "You have latest cabal extras script"
+    fi
+}
+
+#
 # Load up the repl in "quick" mode.
 #
 run_quick () {
     initialize
-    [ $# -eq 1 ] || fail "Quick requires a single argument, specifying the entry point you want to load."
+    [ $# -eq 1 ] || fail "'quick' requires a single argument, specifying the entry point you want to load."
     [ -f "$1" ] || fail "The entry point does not exist."
     [ ! -d src ] || SRC_DIRS="-isrc"
     [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
     [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
     ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} "$1"
+}
+
+#
+# Load up ghcid
+#
+run_watch () {
+    command -v ghcid >/dev/null 2>&1 || { echo >&2 "ghcid required not installed. To install: create a fresh cabal sandbox, cabal install ghcid and add to your \$PATH."; exit 1; }
+    initialize
+    [ $# -ge 1 ] || fail "Watch requires at least one argument, specifying the entry point you want to load."
+    [ -f "$1" ] || fail "The entry point does not exist."
+    [ ! -d src ] || SRC_DIRS="-isrc"
+    [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
+    [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
+    ENTRY=$1
+    shift
+    ghcid -c "ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} \"$ENTRY\"" "$@"
 }
 
 #
@@ -122,26 +178,124 @@ run_clean () {
 }
 
 #
-# Build and run the configured demonstration executable.
+# Dependency tools.
 #
-run_demo () {
-    echo "Someone should really implement this."
-    exit 1
+
+# using this instead of git submodule foreach in the hope I can avoid recursive submodule init/updates (probably can't though, so this may be irrelevant).
+list_modules () {
+    [ $# -eq 1 ] || fail "list_modules requires a single argument, specifying the root of the project."
+    MODULES="$1/.gitmodules"
+    if [ -f "${MODULES}" ]; then
+        grep path "${MODULES}" | sed 's/.*= //'
+    fi
+}
+
+force_sync () {
+    [ $# -eq 1 ] || fail "force sync requires a single argument, specifying the root of the project."
+    SYNC_ROOT="$1"
+    (
+        cd "${SYNC_ROOT}" ## required for submodule commands on older versions of git
+        git fetch
+        git submodule init
+        git submodule update
+        git submodule sync
+    ) > /dev/null 2>&1
+}
+
+run_depend_check () {
+    TOP=$(git rev-parse --show-toplevel)
+    force_sync "${TOP}"
+    list_modules "${TOP}" | while read SUBMODULE; do
+        (
+            cd "${TOP}/${SUBMODULE}"
+            echo "$SUBMODULE"
+            git fetch > /dev/null 2>&1
+            OUT=$(git rev-list --left-right --count origin/master...)
+            BEHIND=$(echo $OUT | awk '{ print $1 }')
+            AHEAD=$(echo $OUT | awk '{ print $2 }')
+
+            if [ "$AHEAD" -eq 0 -a "$BEHIND" -eq 0 ]; then
+                echo '  `- [OK]'
+            elif [ "$AHEAD" -eq 0 -a "$BEHIND" -gt 0 ]; then
+                echo '  `- [WARNING] Behind master.'
+            elif [ "$AHEAD" -gt 0 -a "$BEHIND" -eq 0 ]; then
+                echo '  `- [WARNING] Commits not on master.'
+            elif [ "$AHEAD" -gt 0 -a "$BEHIND" -gt 0 ]; then
+                echo '  `- [WARNING] Commits not on master & behind master.'
+            fi
+        )
+    done
+}
+
+run_depend_deep_check () {
+    TOP=$(git rev-parse --show-toplevel)
+    force_sync "${TOP}"
+    list_modules "${TOP}" | while read SUBMODULE; do
+        (
+            echo "$SUBMODULE"
+            force_sync "${TOP}/${SUBMODULE}"
+            list_modules "${TOP}/${SUBMODULE}" | while read SUBSUBMODULE; do
+                if [ -e "${TOP}/${SUBSUBMODULE}" ]; then
+                    NESTED=$(cd "${TOP}/${SUBMODULE}/${SUBSUBMODULE}" > /dev/null 2>&1; git rev-parse HEAD);
+                    OUTER=$(cd "${TOP}/${SUBSUBMODULE}" > /dev/null 2>&1; git rev-parse HEAD);
+                    if [ "${NESTED}" = "${OUTER}" ]; then
+                        echo "  \`- [OK] ${SUBSUBMODULE}"
+                    else
+                        (
+                            cd "${TOP}/${SUBSUBMODULE}"
+                            git fetch > /dev/null 2>&1
+                            echo ${TOP}/${SUBSUBMODULE}
+                            OUT=$(git rev-list --left-right --count "${NESTED}...${OUTER}")
+                            BEHIND=$(echo $OUT | awk '{ print $1 }')
+                            AHEAD=$(echo $OUT | awk '{ print $2 }')
+                            echo "  \`- [WARNING] ${SUBSUBMODULE} is out of sync, outer commit ${OUTER}, nested ${NESTED}, outer is ${BEHIND} commits behind, ${AHEAD} commits ahead."
+                        )
+                    fi
+                else
+                    echo "  \`- [WARNING] Potentially missing dependency ${SUBSUBMODULE}"
+                fi
+            done
+        )
+    done
+}
+
+run_depend_sync () {
+    TOP=$(git rev-parse --show-toplevel)
+    list_modules "${TOP}" | while read SUBMODULE; do
+        (
+            echo "$SUBMODULE"
+            force_sync "${TOP}/${SUBMODULE}"
+
+            cd "${TOP}/${SUBMODULE}"
+            if git branch -a | grep -q origin/ambiata; then
+                git checkout ambiata
+                git merge origin/ambiata
+            else
+                git checkout master
+                git merge origin/master
+            fi
+
+            force_sync "${TOP}/${SUBMODULE}"
+        )
+    done
+}
+
+run_depend () {
+    [ $# -eq 1 ] || fail "'depend' requires a single argument, specifying the mode as one of [check|deep-check|sync]."
+
+    case "$1" in
+    check) run_depend_check ;;
+    deep-check) run_depend_deep_check ;;
+    sync) run_depend_sync;;
+    *) fail "Unknown mode [$1], expected one of [check|deep-check|sync]" ;;
+    esac
 }
 
 #
-# Build and run the configured application executable.
-#
-run_exec () {
-    echo "Someone should really implement this."
-    exit 1
-}
-
-#
-# Run hasktags on this project (building hlint if necessary).
+# Run hasktags on this project.
 #
 run_tags () {
-    # should install hasktags if it doesn't exist yet.
+    # TODO should install hasktags if it doesn't exist yet.
     hasktags -e src test main
 }
 
@@ -149,18 +303,8 @@ run_tags () {
 # Run hlint on this project (building hlint if necessary).
 #
 run_lint () {
-    # do something with hlint - need to work out best convention to build up
-    echo "Someone should really implement this."
-    exit 1
-}
-
-#
-# Initialize an empty project with a reasonable skeleton.
-#
-run_init () {
-    # make sure there is an empty directory and fill out skeleton
-    echo "Someone should really implement this."
-    exit 1
+    # TODO should install hlint if it doesn't exist yet.
+    hlint src test main
 }
 
 #
@@ -188,6 +332,7 @@ esac
 
 MODE="$1"; shift
 case "$MODE" in
-build|test|repl|quick|demo|exec|tags|lint|init|update|clean) run_$MODE "$@" ;;
+build|test|repl|quick|tags|lint|update|clean|depend|watch|upgrade) run_$MODE "$@" ;;
 *) fail "Unknown mode: $MODE"
 esac
+# Version: 7aa6d8bd13b8cba10f8d534add0098096b7c24fa
